"""Theme processing and CSS generation for BARQUE"""

from pathlib import Path
from typing import Dict
from .config import BarqueConfig


class ThemeProcessor:
    """Process and generate theme-specific CSS"""

    def __init__(self, config: BarqueConfig):
        self.config = config

    def generate_css(self, theme: str) -> str:
        """Generate CSS for specified theme (light or dark)"""
        theme_data = self._get_theme_data(theme)

        css = f"""
/* BARQUE Generated Theme: {theme.upper()} */
/* Generated by BARQUE v2.0.0 */

:root {{
    /* Theme Colors */
    --bg-primary: {theme_data.get('background', '#ffffff')};
    --bg-secondary: {self._lighten_darken(theme_data.get('background', '#ffffff'), 0.05)};
    --text-primary: {theme_data.get('text', '#000000')};
    --text-secondary: {self._lighten_darken(theme_data.get('text', '#000000'), -0.2)};
    --border-color: {theme_data.get('border', '#e0e0e0')};
    --accent-color: {theme_data.get('accent', '#2563eb')};
    --code-bg: {theme_data.get('code_bg', '#f0f0f0')};
    --code-text: {theme_data.get('code_text', theme_data.get('text', '#000000'))};
    --link-color: {theme_data.get('accent', '#2563eb')};
    --link-hover: {self._lighten_darken(theme_data.get('accent', '#2563eb'), -0.1)};

    /* Typography */
    --font-family: {self.config.font_family};
    --base-font-size: {self.config.base_font_size};
    --line-height: {self.config.line_height};
    --max-width: {self.config.max_width};
}}

/* Base Styles */
* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

html {{
    font-size: var(--base-font-size);
}}

body {{
    background-color: var(--bg-primary);
    color: var(--text-primary);
    font-family: var(--font-family);
    line-height: var(--line-height);
    max-width: var(--max-width);
    margin: 0 auto;
    padding: 40px 20px;
}}

/* Typography */
h1, h2, h3, h4, h5, h6 {{
    color: var(--text-primary);
    margin-top: 2em;
    margin-bottom: 1em;
    font-weight: 600;
    line-height: 1.3;
}}

h1 {{
    font-size: 2.5em;
    border-bottom: 3px solid var(--accent-color);
    padding-bottom: 0.5em;
}}

h2 {{
    font-size: 2em;
    border-bottom: 2px solid var(--border-color);
    padding-bottom: 0.5em;
}}

h3 {{
    font-size: 1.5em;
}}

h4 {{
    font-size: 1.25em;
}}

h5 {{
    font-size: 1.1em;
}}

h6 {{
    font-size: 1em;
    font-weight: 600;
}}

p {{
    margin-bottom: 1em;
    text-align: justify;
}}

/* Links */
a {{
    color: var(--link-color);
    text-decoration: none;
    border-bottom: 1px solid transparent;
    transition: all 0.2s ease;
}}

a:hover {{
    color: var(--link-hover);
    border-bottom-color: var(--link-hover);
}}

/* Lists */
ul, ol {{
    margin-left: 2em;
    margin-bottom: 1em;
}}

li {{
    margin-bottom: 0.5em;
}}

/* Code Blocks */
code {{
    background-color: var(--code-bg);
    color: var(--code-text);
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
    font-size: 0.9em;
}}

pre {{
    background-color: var(--code-bg);
    color: var(--code-text);
    padding: 1.5em;
    border-radius: 6px;
    overflow-x: auto;
    margin-bottom: 1em;
    border-left: 4px solid var(--accent-color);
}}

pre code {{
    background: none;
    padding: 0;
    font-size: 0.95em;
}}

/* Blockquotes */
blockquote {{
    border-left: 4px solid var(--accent-color);
    padding-left: 1.5em;
    margin: 1.5em 0;
    color: var(--text-secondary);
    font-style: italic;
}}

/* Tables */
table {{
    width: 100%;
    border-collapse: collapse;
    margin: 2em 0;
}}

th, td {{
    padding: 12px 15px;
    text-align: left;
    border-bottom: 1px solid var(--border-color);
}}

th {{
    background-color: var(--bg-secondary);
    font-weight: 600;
    color: var(--text-primary);
    border-bottom: 2px solid var(--accent-color);
}}

tr:hover {{
    background-color: var(--bg-secondary);
}}

/* Images */
img {{
    max-width: 100%;
    height: auto;
    display: block;
    margin: 2em auto;
    border-radius: 6px;
}}

/* Horizontal Rule */
hr {{
    border: none;
    border-top: 2px solid var(--border-color);
    margin: 3em 0;
}}

/* Mathematical Formulas */
.math-inline {{
    color: var(--text-primary);
}}

.math-display {{
    overflow-x: auto;
    padding: 1em 0;
    text-align: center;
}}

/* MathJax/KaTeX Support */
mjx-container[jax="CHTML"],
.katex-display {{
    margin: 1em 0;
}}

/* Table of Contents */
nav#TOC {{
    background-color: var(--bg-secondary);
    padding: 1.5em;
    border-radius: 6px;
    margin-bottom: 2em;
    border-left: 4px solid var(--accent-color);
}}

nav#TOC ul {{
    list-style: none;
    margin-left: 0;
}}

nav#TOC li {{
    margin-bottom: 0.5em;
}}

nav#TOC a {{
    color: var(--text-primary);
}}

nav#TOC a:hover {{
    color: var(--accent-color);
}}

/* Print Styles */
@media print {{
    body {{
        max-width: 100%;
        padding: 0;
    }}

    a {{
        color: var(--text-primary);
        text-decoration: none;
    }}

    pre {{
        page-break-inside: avoid;
    }}
}}

/* Responsive */
@media (max-width: 768px) {{
    body {{
        padding: 20px 15px;
    }}

    h1 {{
        font-size: 2em;
    }}

    h2 {{
        font-size: 1.6em;
    }}

    pre {{
        padding: 1em;
    }}
}}
"""
        return css

    def save_theme_css(self, theme: str, output_dir: Path) -> Path:
        """Save theme CSS to file"""
        css = self.generate_css(theme)
        css_file = output_dir / f"{theme}-theme.css"
        css_file.parent.mkdir(parents=True, exist_ok=True)
        css_file.write_text(css, encoding='utf-8')
        return css_file

    def _get_theme_data(self, theme: str) -> Dict[str, str]:
        """Get theme data for specified theme"""
        if theme == "light":
            return self.config.light_theme
        elif theme == "dark":
            return self.config.dark_theme
        else:
            raise ValueError(f"Unknown theme: {theme}")

    @staticmethod
    def _lighten_darken(color: str, amount: float) -> str:
        """
        Lighten or darken a hex color
        amount: -1.0 to 1.0 (negative = darken, positive = lighten)
        """
        # Remove '#' if present
        color = color.lstrip('#')

        # Convert hex to RGB
        r, g, b = int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16)

        # Adjust brightness
        if amount > 0:  # Lighten
            r = int(r + (255 - r) * amount)
            g = int(g + (255 - g) * amount)
            b = int(b + (255 - b) * amount)
        else:  # Darken
            amount = abs(amount)
            r = int(r * (1 - amount))
            g = int(g * (1 - amount))
            b = int(b * (1 - amount))

        # Clamp values
        r = max(0, min(255, r))
        g = max(0, min(255, g))
        b = max(0, min(255, b))

        # Convert back to hex
        return f"#{r:02x}{g:02x}{b:02x}"
