"""Theme processing and CSS generation for BARQUE"""

from pathlib import Path
from typing import Dict
from .config import BarqueConfig


class ThemeProcessor:
    """Process and generate theme-specific CSS"""

    def __init__(self, config: BarqueConfig):
        self.config = config

    def generate_css(self, theme: str) -> str:
        """Generate CSS for specified theme (light or dark)"""
        theme_data = self._get_theme_data(theme)

        # Calculate enhanced code block colors for better contrast
        bg_color = theme_data.get('background', '#ffffff')
        code_bg = theme_data.get('code_bg', '#f0f0f0')

        # For dark theme, make code blocks more distinct
        if theme == "dark":
            # Lighter code background for better contrast against dark body
            code_bg_enhanced = self._lighten_darken(code_bg, 0.15)
            code_border = self._lighten_darken(code_bg, 0.25)
        else:
            code_bg_enhanced = code_bg
            code_border = self._lighten_darken(code_bg, -0.1)

        # Use slightly larger font for better readability (16px instead of 14px)
        base_font = self.config.base_font_size
        if base_font == "14px":
            base_font = "16px"

        css = f"""
/* BARQUE Generated Theme: {theme.upper()} */
/* Generated by BARQUE v2.1.0 - Enhanced Dark Mode */

/* PAGE RULES - Critical for PDF background (eliminates white margins) */
@page {{
    background-color: {bg_color};
    margin: 1cm;
    @top-center {{
        content: none;
    }}
    @bottom-center {{
        content: counter(page);
        color: {theme_data.get('text', '#000000')};
        font-size: 10px;
    }}
}}

:root {{
    /* Theme Colors */
    --bg-primary: {bg_color};
    --bg-secondary: {self._lighten_darken(bg_color, 0.05 if theme == "dark" else -0.03)};
    --text-primary: {theme_data.get('text', '#000000')};
    --text-secondary: {self._lighten_darken(theme_data.get('text', '#000000'), -0.2 if theme == "light" else 0.15)};
    --border-color: {theme_data.get('border', '#e0e0e0')};
    --accent-color: {theme_data.get('accent', '#2563eb')};
    --code-bg: {code_bg_enhanced};
    --code-border: {code_border};
    --code-text: {theme_data.get('code_text', theme_data.get('text', '#000000'))};
    --link-color: {theme_data.get('accent', '#2563eb')};
    --link-hover: {self._lighten_darken(theme_data.get('accent', '#2563eb'), -0.1)};

    /* Typography - Enhanced for readability */
    --font-family: {self.config.font_family};
    --base-font-size: {base_font};
    --line-height: {self.config.line_height};
    --max-width: {self.config.max_width};
}}

/* Base Styles */
* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

/* HTML and Body background - ensures full coverage */
html {{
    font-size: var(--base-font-size);
    background-color: var(--bg-primary);
}}

body {{
    background-color: var(--bg-primary);
    color: var(--text-primary);
    font-family: var(--font-family);
    line-height: var(--line-height);
    max-width: var(--max-width);
    margin: 0 auto;
    padding: 40px 20px;
}}

/* Typography */
h1, h2, h3, h4, h5, h6 {{
    color: var(--text-primary);
    margin-top: 2em;
    margin-bottom: 1em;
    font-weight: 600;
    line-height: 1.3;
}}

h1 {{
    font-size: 2.5em;
    border-bottom: 3px solid var(--accent-color);
    padding-bottom: 0.5em;
}}

h2 {{
    font-size: 2em;
    border-bottom: 2px solid var(--border-color);
    padding-bottom: 0.5em;
}}

h3 {{
    font-size: 1.5em;
}}

h4 {{
    font-size: 1.25em;
}}

h5 {{
    font-size: 1.1em;
}}

h6 {{
    font-size: 1em;
    font-weight: 600;
}}

p {{
    margin-bottom: 1em;
    text-align: justify;
}}

/* Links */
a {{
    color: var(--link-color);
    text-decoration: none;
    border-bottom: 1px solid transparent;
    transition: all 0.2s ease;
}}

a:hover {{
    color: var(--link-hover);
    border-bottom-color: var(--link-hover);
}}

/* Lists */
ul, ol {{
    margin-left: 2em;
    margin-bottom: 1em;
}}

li {{
    margin-bottom: 0.5em;
}}

/* Code Blocks - Enhanced contrast for dark mode */
code {{
    background-color: var(--code-bg);
    color: var(--code-text);
    padding: 3px 8px;
    border-radius: 4px;
    font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
    font-size: 0.875em;
    border: 1px solid var(--code-border);
}}

pre {{
    background-color: var(--code-bg);
    color: var(--code-text);
    padding: 1.25em 1.5em;
    border-radius: 8px;
    overflow-x: auto;
    margin: 1.5em 0;
    border: 1px solid var(--code-border);
    border-left: 4px solid var(--accent-color);
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.15);
}}

pre code {{
    background: none;
    padding: 0;
    border: none;
    font-size: 0.9em;
    line-height: 1.5;
}}

/* Blockquotes */
blockquote {{
    border-left: 4px solid var(--accent-color);
    padding-left: 1.5em;
    margin: 1.5em 0;
    color: var(--text-secondary);
    font-style: italic;
}}

/* Tables */
table {{
    width: 100%;
    border-collapse: collapse;
    margin: 2em 0;
}}

th, td {{
    padding: 12px 15px;
    text-align: left;
    border-bottom: 1px solid var(--border-color);
}}

th {{
    background-color: var(--bg-secondary);
    font-weight: 600;
    color: var(--text-primary);
    border-bottom: 2px solid var(--accent-color);
}}

tr:hover {{
    background-color: var(--bg-secondary);
}}

/* Images */
img {{
    max-width: 100%;
    height: auto;
    display: block;
    margin: 2em auto;
    border-radius: 6px;
}}

/* Horizontal Rule */
hr {{
    border: none;
    border-top: 2px solid var(--border-color);
    margin: 3em 0;
}}

/* Mathematical Formulas */
.math-inline {{
    color: var(--text-primary);
}}

.math-display {{
    overflow-x: auto;
    padding: 1em 0;
    text-align: center;
}}

/* MathJax/KaTeX Support */
mjx-container[jax="CHTML"],
.katex-display {{
    margin: 1em 0;
}}

/* Table of Contents */
nav#TOC {{
    background-color: var(--bg-secondary);
    padding: 1.5em;
    border-radius: 6px;
    margin-bottom: 2em;
    border-left: 4px solid var(--accent-color);
}}

nav#TOC ul {{
    list-style: none;
    margin-left: 0;
}}

nav#TOC li {{
    margin-bottom: 0.5em;
}}

nav#TOC a {{
    color: var(--text-primary);
}}

nav#TOC a:hover {{
    color: var(--accent-color);
}}

/* Print Styles - Enhanced for PDF generation */
@media print {{
    html, body {{
        background-color: var(--bg-primary) !important;
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
        color-adjust: exact !important;
    }}

    body {{
        max-width: 100%;
        padding: 0;
    }}

    a {{
        color: var(--link-color);
        text-decoration: none;
    }}

    pre, code {{
        background-color: var(--code-bg) !important;
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
    }}

    pre {{
        page-break-inside: avoid;
    }}

    table {{
        page-break-inside: avoid;
    }}

    h1, h2, h3, h4, h5, h6 {{
        page-break-after: avoid;
    }}
}}

/* Responsive */
@media (max-width: 768px) {{
    body {{
        padding: 20px 15px;
    }}

    h1 {{
        font-size: 2em;
    }}

    h2 {{
        font-size: 1.6em;
    }}

    pre {{
        padding: 1em;
    }}
}}
"""
        return css

    def save_theme_css(self, theme: str, output_dir: Path) -> Path:
        """Save theme CSS to file"""
        css = self.generate_css(theme)
        css_file = output_dir / f"{theme}-theme.css"
        css_file.parent.mkdir(parents=True, exist_ok=True)
        css_file.write_text(css, encoding='utf-8')
        return css_file

    def _get_theme_data(self, theme: str) -> Dict[str, str]:
        """Get theme data for specified theme"""
        if theme == "light":
            return self.config.light_theme
        elif theme == "dark":
            return self.config.dark_theme
        else:
            raise ValueError(f"Unknown theme: {theme}")

    @staticmethod
    def _lighten_darken(color: str, amount: float) -> str:
        """
        Lighten or darken a hex color
        amount: -1.0 to 1.0 (negative = darken, positive = lighten)
        """
        # Remove '#' if present
        color = color.lstrip('#')

        # Convert hex to RGB
        r, g, b = int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16)

        # Adjust brightness
        if amount > 0:  # Lighten
            r = int(r + (255 - r) * amount)
            g = int(g + (255 - g) * amount)
            b = int(b + (255 - b) * amount)
        else:  # Darken
            amount = abs(amount)
            r = int(r * (1 - amount))
            g = int(g * (1 - amount))
            b = int(b * (1 - amount))

        # Clamp values
        r = max(0, min(255, r))
        g = max(0, min(255, g))
        b = max(0, min(255, b))

        # Convert back to hex
        return f"#{r:02x}{g:02x}{b:02x}"
